### ISSUE TITLE
Redesign of `vfatmask` usage

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#101]
Looking at recent issue #97 does this script really need a `vfatmask`?
I think if it does we've made some wrong choices...
* The mask should *only* be necessary when there's a VFAT missing that will cause a register transaction to fail, i.e., only in the scan scripts themselves.
* The analysis needs to be robust enough to ignore VFATs for which it has no data.
* Propagating this `vfatmask` through many layers of tools is definitely the wrong way to design this.
* In fact, everything can even be made smart enough to *not* need the `vfatmask` anywhere, as we can get a list of connected VFATs and convert this to a mask.
  * Though the mask does allow one to "turn off" VFATs which are not problematic but may want to be ignored for some reason

**Comment by lmoureaux** [comment]
`anaUltraThreshold` writes a `vfatConfig.txt` and a `chConfig.txt`, and the `vfatmask` is also used for output. It allows one to choose the list of VFATs that are included in the config files. I don't know if this feature is intentional.
It looks like one can get rid of the `vfatmask` argument rather easily. I have an initial patch that needs some testing.

**Comment by bdorney** [comment]
Is this re-design still needed? Right now the analysis tools in `gem-plotting-tools` no longer user `vfatmask`:

```
% cd ../gem-plotting-tools/ 
% grep -R "vfatmask"       
%  
```

Of the scan tools that use this option:
```
% grep -R "vfatmask"
ultraLatency.py:mask = options.vfatmask
qcoptions.py:parser.add_option("--vfatmask", type="int", dest="vfatmask",
qcoptions.py:                  help="VFATs to be masked in scan & analysis applications (e.g. 0xFFFFF masks all VFATs)", metavar="vfatmask", default=0x0)
run_scans.py:def launchTestsArgs(tool, shelf, slot, link, chamber, vfatmask, scanmin, scanmax, nevts, stepSize=1,
run_scans.py:  cmd = ["%s"%(tool),"-s%i"%(slot),"-g%i"%(link),"--shelf=%i"%(shelf), "--nevts=%i"%(nevts), "--vfatmask=0x%x"%(vfatmask)]
trimChamber.py:            "--vfatmask=0x%x"%(options.vfatmask),
trimChamber.py:                    "--vfatmask=0x%x"%(options.vfatmask),
trimChamber.py:                "--vfatmask=0x%x"%(options.vfatmask),
trimChamber.py:            "--vfatmask=0x%x"%(options.vfatmask),
GEMDAQTestSuite.py:        self.vfatmask = 0xff000000
GEMDAQTestSuite.py:        self.vfatmask = setVFATTrackingMask(self.ohboard,self.gtx)
GEMDAQTestSuite.py:        setVFATTrackingMask(self.ohboard,self.gtx,self.vfatmask)
ultraScurve.py:mask = options.vfatmask
ultraThreshold.py:mask = options.vfatmask
```

The scan tools either:
1. `vfatmask` from command line, or
2. If launched by `run_scans.py` take `vfatmask` from `gem-plotting-tools/mapping/chamberInfo.py` in the form of the `chamber_vfatMask` dict.

One could generate the entries of the `chamber_vfatMask` dict by detecting which vfats are present.  But the current functionality does allow one to turn off problematic vfats.  Given that this appears to be mostly a test stand issue and not a P5 issue I would suggest to leave the current functionality in place and close this issue.

**Comment by jsturdy** [comment]
Agreed
