### ISSUE TITLE
Feature Request: Add "--internal" to run_scans.py

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#107]
Allow run_scans.py to use the internal trigger when running a latency scan.

**Comment by jsturdy** [comment]
What is the purpose for this?

**Comment by bdorney** [comment]
Software testing and debugging...requested by DOC

**Comment by jsturdy** [comment]
I ask because this option is definitely a debug option, and I don't see a strong use case to run it on all chambers simultaneously, so could be kept out of `run_scans` for simplicity
