### ISSUE TITLE
Excessive unnecessary subprocess.call usage

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/vfatqc-python-scripts#120]
## Brief summary of issue

All the unit scripts are called through system calls instead as functions. 
### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

The unit script should look like (~indentation is not preserved by markdown~, now with correct markdown syntax):

```python
def my_function(my_params):
    print "Hello World"
    pass

def main()
    print "Fetch params"
    # fetch params here
    my_function(my_params)

if __name__ == "__main__":
    main()
```

then it can be called from command line as before, but if one needs to call the function `my_function` from another module, it can be done via simple `import`.

## Current Behavior

Instead every time when such a unit script has to be called, the 
`subprocess.call("python my_script.py my parameters")` 
is called.

**Comment by bdorney** [comment]
If I understand correctly what you are proposing is that `anaUltra*.py` go from scripts to functions with a main defined? e.g. for `ultraScurve.py` you would propose to have:

```
def ultraScurve( args ):
    code
    code
    code

    return

if __name__ == "__main__":
    get command line arguments
    ultraScurve( those command line arguments )
```

Correct?

I suppose you propose the same thing for `gem-plotting-tools`?  If so I would suggest to open a similar issue there as well.

Could you highlight or elaborate on the disadvantage of the current implementation?  Specifically:

> Instead every time when such a unit script has to be called, the
subprocess.call("python my_script.py my parameters")
is called.

What does this mean and why is it undesired?

**Comment by mexanick** [comment]
Yes, you're correct about what I want. 
Now, what means "subprocess call involved":

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/1b1944142bd102937c3c71db03023fc7057aecaa/confAllChambers.py#L15-L35

where 

https://github.com/cms-gem-daq-project/cmsgemos/blob/b85f5bb29772760ec22ea772cc02e63dd4623699/gempython/utils/wrappers.py#L2-L22

and this all is happening instead of 
```
from my_module import my_function
my_function(my_args)
```
Considering why the subprocess calls are undesired:
1. It is unnecessary
2. If you will ever want to return some data other then status code, you will have difficulties (it is possible, but way more complicated w.r.t. regular python functions)
3. There's an overhead to invoke the system call. Not that much, but why should we waste resources?
4. The code is less readable like that and contains quite a number of extra syntax. Using the pythonic way of modules and functions will streamline the code.

**Comment by lmoureaux** [comment]
Playing the Devil's advocate here:

1. Having several processes allows to isolate them (in case of SIGSEGV)
2. In order to get equivalent behavior, you would have to change the current code to:
```python
from my_module import my_function
try:
    my_function(link, shelf, vt1bump=vt1bump, arg1=val1, arg2=val2, arg3=val3)
except SomeError:
    # do something
```
which can quickly become as unreadable as the command line thing, especially for standard arguments such as `-g` or `-s`. Passing all arguments at once just doesn't scale well, be it for command-line tools or functions. Maybe we can make some classes to simplify things, eg
```python
from my_module import my_function
try:
    detConfig = DetectorConfig(link, shelf)
    detConfig.vt1bump = vt1bump # Alternative syntax?
    my_function(detConfig, arg1=val1, arg2=val2, arg3=val3)
except SomeError:
    # do something
```
It's a bit more verbose but also easier to read.

3. Exchanging data through ROOT files enforces some modularity, which is good. It also makes it easier to evaluate new ideas.
4. I guess the additional resource usage from subprocesses is close to negligible, and we'll want to use threads anyway (python threads are additional processes).

Don't take me wrong, I'm in favor of making this change, but it has to be done carefully.

**Comment by mexanick** [comment]
> Having several processes allows to isolate them (in case of SIGSEGV)

Not really needed.

> In order to get equivalent behavior, you would have to change the current code to:

Writing exception-safe code is a different thing. It has nothing to do with the proposed change (although I certainly agree that we should be careful and write exception-safe code)

Considering classes - We may want to add some later, however at the current stage of the project I consider classes as unnecessary complication (we are not going to write enterprise "Hello World", are we?)

> I guess the additional resource usage from subprocesses is close to negligible, and we'll want to use threads anyway (python threads are additional processes).

The main disadvantage of the subprocess calls is not the overhead, but unclear spawning of new processes and complicated I/O redirection, which is manageable, but not required here. 
Also `python threads are additional processes` is just wrong. Python operates with both _threads_ and _processes_ and these are different things. See https://stackoverflow.com/questions/3044580/multiprocessing-vs-threading-python

**Comment by bdorney** [comment]
I think we can close this as most of these tools have been completely re-written and do not use `subprocess.call` now.
