### ISSUE TITLE
Feature Request: ultraLatency.py prints Reg values before launching scan

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#123]
## Brief summary of issue

Have `ultraLatency.py` print a table to the terminal of relevant registers before launching a scan application.  Something like:

| vfat | VT1 | VT2 | MSPL |
| ==== | === | === | ==== |
| 0 | 100 | 0 | 4 |
| 1 | 100 | 0 | 4 |
...
...
| 22 | 100 | 0 | 4 |
| 23 | 100 | 0 | 4 |

Since these scans can take a long time this can allow the user to check either the terminal output, or the `scanLog.log` before the scan finishes that the correct values are used.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

A table is printed to terminal (or log file) that allows the user to xcheck the settings the scan is being taken at.  This will prevent lost time.

## Current Behavior

Presently one has to do a read using either `vfat_info_uhal.py` or via `reg_interface.py` to determine the settings the scan is being taken at in situ or wait until the scan is completed and read them from the TBranches of `latTree`.

## Context (for feature requests)

User might expect from a call of `confChamber.py` that registers are configured as expected.  If registers are not written correctly a large loss of time might be incurred.  This xcheck might prevent such a lost time.

**Comment by jsturdy** [comment]
How is this different from #122?
In fact, I would say that this should be part of `confChamber` only, and not part of any scan routine
One could then can have a `--verify` option which will simply print the current configuration (well, a reasonably chosen subset of the configuration), maybe highlighting differences, and could be run in conjunction with the usual configuration call

**Comment by bdorney** [comment]
If you are executing a measurement program in which scans are taken in succession without repeated calls of `confChamber.py` I think it would be useful to print the configuration before launching the scan.  For example if you are changing the HV applied or at different beam intensities.  To quickly catch potential mistakes I think for those scans that may take a non-zero amount of time I think this would be a good cross-check, and should work in conjunction with https://github.com/cms-gem-daq-project/vfatqc-python-scripts/issues/122

**Comment by jsturdy** [comment]
My point was that you put this in `confChamber.py` and call it with this new option, which only prints out the summary.  The printing of the config is(should be) completely unrelated to the scan you're running, but *is* related to the configuration

**Comment by bdorney** [comment]
I understood your point about it going into `confChamber.py` and I agree, that's why I opened an issue for it.

However If a scan takes 7 hours to complete I'd like to know (and a shifter should know) that it's being done with the correct settings.  I think a print out will help to ensure that, rather than having to wait for the end of the scan to see what's stored in the output TTree or having to use some other tool (e.g. reg_interface).

Given that these register values are already *read* and *stored* by `ultraLatency.py`I don't see the issue with adding this.
