### ISSUE TITLE
Bug Report: run_scans.py spawns additional processes

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#125]
## Brief summary of issue

As shown: http://cmsonline.cern.ch/cms-elog/1007990

`run_scans.py` seems to have spawned 12 processes even though `chamber_config` has only one entry (link 0).  This has been reported before mattermost.  Investigating using `top` seems to show these processes are all stuck/dead and take 0% cpu.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

When `chamber_config` has only one entry you should have `run_scans.py` only launch one additional process.

## Current Behavior

Rarely we see additional processes launched, seems to always be 12, the same as the pool argument (weird...).

### Steps to Reproduce (for bugs)

1. Open `gem-plotting-tools/mapping/chamberInfo.py`
2. Place only a single entry in `chamber_config` dict (also made GEBtype, and chamber_vfatMask dict's only have one entry, chamber_vfatDACSettings is empty).
3. Launch a trim run with run_scans.py

I bet this is not distinct to only trim run.  I also suspect that `confAllChambers.py` and `gem-plotting-tools/ana_scans.py` may suffer a similar problem?

It seems using the `--series` option allows data-taking to continue unimpeded.

## Possible Solution (for bugs)

Not sure...rare...hard to reproduce.

## Your Environment

* Version used: 18496a1506f0312d2834062bce2e5708abc6d583
* Shell used: /bin/zsh (running on gem904daq01)

**Comment by bdorney** [comment]
Another example: http://cmsonline.cern.ch/cms-elog/1009746

**Comment by jsturdy** [comment]
Any verification of this behaviour?

**Comment by bdorney** [comment]
> Any verification of this behaviour?

What do you mean by verification?  Two e-logs linked show pretty clearly that the problem occurs.  Unfortunately I haven't had time to debug it.  With only one active link I've been running everything with the `--series` option.  However now that the cosmicstand has multiple detectors I will try to devote some time to this next week.

**Comment by bdorney** [comment]
Another example: http://cmsonline.cern.ch/cms-elog/1012069

Will have to spend some time debugging this next week.

**Comment by bdorney** [comment]
closing as irrelevant due to refactoring of `run_scans.py`
