### ISSUE TITLE
Feature Request: Filesystem Interaction Before TFile::Write()

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#126]
## Brief summary of issue

On cosmicstandtif it seems the automount of the 904 NAS times out after some time.  When this happens if a scan is running the output TFile will be a zombie and have no keys causing a data loss.  This is especially frustrating if the scans take a long time to run due to low trigger rate (e.g. cosmics).

Issue has occurred several times, one has been reported here: http://cmsonline.cern.ch/cms-elog/1008108

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

I see two ways that this could be solved.  

The first way is to perform a filesystem interaction before writing out the output `TFile`.  For example in `ultraLatency.py` placing before [L#269](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/18496a1506f0312d2834062bce2e5708abc6d583/ultraLatency.py#L269):

```
    from gempython.utils.wrappers import runCommand
    runCommand(["stat",filename])
```

The second way could be to:

1. write the file to a temporary directory on the machine, 
2. check the requested output directory exists, and then
3. move the output file to the output directory at the scan end.

I think the first option is simpler and has already been tested with a local change at:

http://cmsonline.cern.ch/cms-elog/1008108
http://cmsonline.cern.ch/cms-elog/1009162

While latency scans are potentially the longest ultra scans we have right now I would suggest adding this to all of the scan modules:

- `fastLatency.py`,
- `ultraLatency.py`,
- `ultraScurve.py`, and
- `ultraThreshold.py`.

## Current Behavior

If the 904 NAS times out during a scan on cosmicstandtif data loss ensues. 

## Context (for feature requests)

Losing a lot of time and data due to low trigger rate (cosmics).

## Your Environment

* Version used: 18496a1506f0312d2834062bce2e5708abc6d583
* Shell used: /bin/bash

**Comment by mexanick** [comment]
Becomes irrelevant after migration to CC7
