### ISSUE TITLE
Bug Report: ultraLatency.py Does Not Record Correct vth1 Values?

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#128]
## Brief summary of issue

Stumbled on a potential bug.  It looks like `vth1` is not correctly being written to `latTree` by `ultraLatency.py` 

In the latency scan reported at this [E-Log](http://cmsonline.cern.ch/cms-elog/1009271) with `scandate=2017.09.12.14.24`.

The `--vfatConfig` used is:
```
/data/bigdisk/GEM-Data-Taking/GE11_QC8/configs/z4.0/vfatConfig_GE11-VI-L-CERN-0001.txt
```

Here `vt1bump=0`.  

In this case I ran `vfat_info_uhal.py` after configuring, but before running the scan, to xcheck the configuration (this was after fixing [this bug](https://github.com/cms-gem-daq-project/cmsgemos/pull/141)).  In this case `VThreshold1` register values match what is in `--vfatConfig`.

However when the scan completed the `vth1` values stored in `latTree` are incorrect from VFAT10 onward.
<img width="478" alt="treedraw_vth1_vs_vfatn_scandate2017 09 12 14 24" src="https://user-images.githubusercontent.com/6432141/30415582-f4e61582-9928-11e7-945e-c1bb0bcd78da.png">

Specifically:

| VFAT | vfatConfig | Elog (Hex) | Elog (Dec) | latTree |
| ---- | ---------- | ---------- | ---------- | ------- |
| 0 | 104 | 0x68 | 104 | 104 |
| 1 | 51 | 0x33 | 51 | 51 |
| 2 | 70 | 0x46 | 70 | 70 |
| 3 | 82 | 0x52 | 82 | 82 |
| 4 | 110 | 0x6e | 110 | 110 |
| 5 | 113 | 0x71 | 113 | 113 |
| 6 | 119 | 0x77 | 119 | 119 |
| 7 | 139 | 0x8b | 139 | 139 |
| 8 | 38 | 0x26 | 38 | 38 |
| 9 | 42 | 0x2a | 42 | 42 |
| 10 | 0 | 0x0 | 0 | 54 |
| 11 | 54 | 0x36 | 54 | 58 |
| 12 | 58 | 0x3a | 58 | 69 |
| 13 | 60 | 0x3c | 60 | 74 |
| 14 | 74 | 0x4a | 74 | 111 |
| 15 | 111 | 0x6f | 111 | 56 |
| 16 | 56 | 0x38 | 56 | 54 |
| 17 | 54 | 0x36 | 54 | 60 |
| 18 | 0 | 0x0 | 0 | 0 |
| 19 | 60 | 0x3c | 60 | 0 |
| 20 | 0 | 0x0 | 0 | 0 |
| 21 | 0 | 0x0 | 0 | 0 |
| 22 | 0 | 0x0 | 0 | 0 |
| 23 | 0 | 0x0 | 0 | 0 |

From VFAT10 -> 16 it looks like everything is shifted by 1.  While VFAT17 appears to be shifted by 2.

Note on the cosmic stand setup VFAT slots 10, 18, 20-23 do not work.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Expect the values stored in the `vth1` branch of `latTree` to match with the parameters that are written at configuration before the scan is launched.

## Current Behavior

The values stored in `vth1` branch of `latTree` do not match the parameters that are written at configuration before the scan is launched.

Additionally I would guess the following scandates are all affected:

2017.08.30.15.03
2017.08.30.21.39
2017.08.31.08.28
2017.09.13.16.45

These are all found in:

```
/data/bigdisk/GEM-Data-Taking/GE11_QC8/GE11-VI-L-CERN-0001/latency/trk
```

The scan logs can all be found there as well.

### Steps to Reproduce (for bugs)

1. Configure with `--vfatConfig` option.
2. Check configuration with `vfat_info_uhal.py`
3. Run a latency scan using `run_scans.py`
4. Plot `vth1` vs. `vfatN`

I tried to reproduce the problem on the 904 integration stand:
http://cmsonline.cern.ch/cms-elog/1009623

But was unsuccessful, `vth1` matches the input configuration in the output `latTree`.

However, the 904 integration stand does not have dead VFAT positions.  I wonder if this is somehow related?

## Possible Solution (for bugs)

No idea yet...

## Your Environment

* Version used: 18496a1506f0312d2834062bce2e5708abc6d583  (Probably) 
* Shell used: /bin/bash

**Comment by jsturdy** [comment]
Directly related to cms-gem-daq-project/cmsgemos#146

**Comment by bdorney** [comment]
In the short-term it looks like `ultraLatency.py` will not crash if `--vfatmask` is not used (e.g. has a value of `0x0`).  So suggest to proceed like this for latency scans on the cosmic stand.

Tested: http://cmsonline.cern.ch/cms-elog/1009678

**Comment by bdorney** [comment]
Based on the discussion:

https://github.com/cms-gem-daq-project/cmsgemos/issues/146

It seems the best thing to do is to *not* provided the mask argument to the calls of `readAllVFATs(...)` in [L127-135](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/126548ef7d2cf9f061d74e9ec6870e0e4a3e2dfa/ultraLatency.py#L127)
