### ISSUE TITLE
Feature Request: Ensure TTC & SCA Info in scanLog.log

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#139]
## Brief summary of issue

Recommendation from @mexanick to ensure TTC info and BC0 info in scanLog.log file for all scans if a scan is produced by `run_scans.py`.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

At the start of each scan module, i.e.

- fastLatency.py
- ultraLatency.py
- ultraScurve.py
- ultraThreshold.py

Insert the following lines:
```
from gempython.utils.wrappers import runCommand

cmd = ["amc_info_uhal.py","--shelf=%i"%options.shelf,"--s%i"%options.gtx,"--short"]
runCommand(cmd)
```

This will ensure that in the `scanLog.log` file the:

- `GEM SYSTEM TTC INFORMATION`, and
- `GEM SYSTEM SCA INFORMATION`

Is printed.

## Current Behavior

This information is not printed in the `scanLog.log` file.

## Context (for feature requests)

Provides unambiguous knowledge of SCA and TTC states when scans are launched.

**Comment by jsturdy** [comment]
Closed by #140
