### ISSUE TITLE
Feature Request: trimChambers.py adds --L1Atime, --pulseDelay, and --latency options

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#142]
## Brief summary of issue

Found that default `--L1Atime`, `--pulseDelay` and `--latency` options for `ultraScurve.py` cannot be tuned during trimming.  Suggest to add these options to `trimChamber.py`.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

Performing a trim run should allow the user to specify `--L1Atime`, `--pulseDelay`, and `--latency` parameters.  This should be applied to all the scurves launched by `trimChamber.py`:

```
trimChamber.py --shelf=1 -s3 -g1 --ztrim=4 --L1Atime=200 --pulseDelay=20 --latency=16
```

Additionally if the scan is launched from `run_scans.py` the same functionality should exist:

```
run_scans.py --shelf=3 -s2 --tool=trimChamber.py --ztrim=4 --L1Atime=200 --pulseDela=20 --latency=16
```

## Current Behavior

It is not possible to specify from `trimChamber.py` or `run_scans.py` the L1Atime, pulseDelay, or Latency for a scan.

**Comment by bdorney** [comment]
Relevant:
http://cmsonline.cern.ch/cms-elog/1016927
http://cmsonline.cern.ch/cms-elog/1016414

We found that for GE11-X-S-CERN-0001 with OH#4 on Link 1 of the cosmic stand that the scurves we were taking only have 50% occupancy in the plateau when using the default:

- `--L1Atime`, 
- `--pulseDelay`, and 
- `--latency` 

As can be seen in above elogs after choosing these parameters correctly we were able to recover the expected occupancy in the scurve plateau region.

Conclude that these options need to be transferable when calling `trimChamber.py` or `run_scans.py`

**Comment by jsturdy** [comment]
Wouldn't it make more sense to just have `trimChamber` do a latency scan?
This way one's not passing around so many options, it's easier to keep track of what's being run, and it's taken care of automatically?

**Comment by bdorney** [comment]
closing as legacy.
