### ISSUE TITLE
Feature request: Vcal scan routines (deep cut characterization)

### ISSUE THREAD

**Issue by cbravo135** [cms-gem-daq-project/vfatqc-python-scripts#143]
## Brief summary of issue
Full VCAL (CAL_DAC) scans are still not straight forward to take within this framework.
The DAQ operation would be to set MSPL (PS) set to 1 and take an scurve at every latency which
will have non-zero hits. An initial latency scan could be used to determine which latency values are
likely to have hits to speed up the data taking process. This set of scans should then be taken
while another DAC is being changed, for example VT1 (ARM_DAC) is a pretty useful DAC to
study with this technique. Please see my IComp study from June for an example of this type
of operation: https://indico.cern.ch/event/643475/contributions/2614566/attachments/1469628/2273413/icompStudy.pdf
This type of scan can be used in characterization and is also a useful tool for debugging at times.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior
Take a large number of scruves and organize them to be analyzed later.

## Current Behavior
I have my own personal custom scripts to do this, but we probably don't want the average
user to be using these.

## Context (for feature requests)
It doesn't exist and we would like to take this type of data while characterizing the V3 electronics.
It could also be used to compare v2 chambers and give insight into large changes observed in
behavior over time.

**Comment by bdorney** [comment]
# Proposal
I think in general it would be good if the scan scan routines had a `--scanAgainst` option which defaults to `None`.  When this is not supplied the existing behavior occurs, e.g. a scan is taken.  

When `--scanAgainst` is supplied the the scan routine takes some range of the `--scanAgainst` register (e.g. 0 -> 255) for a given step size (e.g. 10) and executes one scan for each value of of `--scanAgainst`.

Specifically:

```
ultraX.py --shelf=3 -s2 -g1
```

Would take a single scan while:

```
 ultraX.py --shelf=3 -s2 -g1 --scanAgainst=Latency
```

Would take an `X` scan for each value of latency {0, 10, 20, ..., 240, 250} where the steps of the `--scanAgainst` register are either hard coded or user supplied.

# Past Context
Relevant:
http://cmsonline.cern.ch/cms-elog/1016927
http://cmsonline.cern.ch/cms-elog/1016414

We found that for GE11-X-S-CERN-0001 with OH#4 on Link 1 of the cosmic stand that the scurves we were taking only have 50% occupancy in the plateau.  

The default `--L1Atime`, `--pulseDelay`, and `--latency` for this detector was not sufficienct as compared to what was achieved with GE11-VI-L-CERN-0001 with unlabeled OH on the cosmic stand before it was moved to the coffin.  For example see this old scan taken by @lmoureaux:

http://cmsonline.cern.ch/cms-elog/1005623

Here the scurves reached 100% in the plateau without having to modify the `--L1Atime`, `--pulseDelay`, or `--latency` values away from the default.

If we had been able to use the `--scanAgainst` option we would have arrived at the correct scurve sets automatically.

**Comment by mexanick** [comment]
I don't like the suggested change. It will make ultraX scans more complex and hard to maintain/support. While I fully support the idea of automatic calibration studies, it should be implemented in a different way. I would add an automator-like overhead which will take a certain configuration file (or eventually cmd options, but it might be too much of options...) and then run existing routines needed amount of times with needed parameters updated each time.

**Comment by jsturdy** [comment]
I agree, as @cbravo135 already has a set of scripts to do the type of study he is mentioning (which can probably be generalized), it would probably be best to use that as a starting point, probably something akin to `run_scans` where one defines the measurement routine based around a specific scan type, and then this tool takes care of that.
The `ultraX` then doesn't need to change to adapt, and remains flexible.  It should pretty much be only responsible for configuring the scan against the DAC in question (`VCal`, `Latency`, `VT1`, etc), and creating the output tree.  This is how the trim routine is using the scan, so a generic study should be the same.

**Comment by bdorney** [comment]
Closing as stale.
