### ISSUE TITLE
Feature Request: Resume a trim run

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#147]
## Brief summary of issue

Trim runs take a lot of time.  Occasionally they crash or fail to complete successfully.  However usually they will write out *some* of their data (e.g. the first few scurves will have completed successfully but at some point the scan will fail).  Would like that the functionality exists to resume a trim run from the last successfully produced scurve output file

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

If a trim run crashes or fails to complete but some of the data is present, e.g.:

```
% cd /gemdata/GE11-X-S-CERN-0001/trim/z4.000000/current
% ll              
total 7.7M
-rw-r--r--. 1 dorney zh 314K Oct 24 09:38 scanLog.log
-rw-r--r--. 1 dorney zh 1.9M Oct 23 20:09 SCurveData_trimdac0_range0.root
-rw-r--r--. 1 dorney zh 2.0M Oct 23 20:40 SCurveData_trimdac31_range0.root
-rw-r--r--. 1 dorney zh 1.9M Oct 23 20:58 SCurveData_trimdac31_range1.root
-rw-r--r--. 1 dorney zh 404 Oct 24 07:16 SCurveData_trimdac31_range2.root
```

Here the the last scurve `SCurveData_trimdac31_range2.root` failed to complete (e.g. almost null size).  I would like the ability to call:

```
trimChamber.py --shelf=3 -s2 -g1 --resume --origDir=/gemdata/GE11-X-S-CERN-0001/trim/z4.000000/current
```

It should then identify that the first three scurves completed successfully, e.g. `SCurveData_trimdac0_range0.root` through `SCurveData_trimdac31_range1.root`, but the last one did not and then resume the scan by restarting the scurve: `SCurveData_trimdac31_range2.root`.

It should also be able to determine the original `--ztrim` value that was used.  We might need to add this to the output `TTree` that is produced by `ultraScurve.py` or it could check the `--origDir` path to get it; although I think having it in the `TTree` is more reliable and path independent.

To do this one way might be when performing the binary search step script could check if a given  `SCurveData_trimdacX_rangeY.root` file exists.  If it doesn't exist then the current behavior is executed (e.g. take the scan).  If it does exist instead it should try to fit the data and then use these results to move to the next step in the binary search.

## Current Behavior

If there is a problem during a trim run we loose a lot of time and data has to be repeatedly re-taken.

## Context (for feature requests)

Right now we only have to manage a max of 9-10 detectors in a system.  In the future this number will be 30 (QC8) or 144 in (P5).  It would be good to be able to resume partially completed trim runs.

**Comment by jsturdy** [comment]
At some point, I think that @cbravo135 had some way to have this working

**Comment by bdorney** [comment]
Closing as stale, resolved in v3 branch.
