### ISSUE TITLE
Feature Request: ultra scans print SCA & TTC information at the end of the scan

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#148]
## Brief summary of issue

The ultra scans should presently (in `develop`) print the SCA & TTC information at the start of a scan, we would like that they also all print this information at the end of the scan.

This will ensure that any changes in the TTC or LHC clock during a scan are caught in the scan log.  This can be helpful for understanding results after they are taken.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

At the end of each of the ultra scans the following lines should be added such that their output is included in the `scanLog.log` file that is created by `run_scans.py`:

```
from gempython.tools.amc_user_functions_uhal import *
amcBoard = getAMCObject(options.slot, options.shelf, options.debug)
printSystemSCAInfo(amcBoard, options.debug)
printSystemTTCInfo(amcBoard, options.debug)
```

## Current Behavior

Right now the SCA & TTC information is printed at only the start of the scan.

## Context (for feature requests)

This will help us catch information such as the TTC status or LHC clock changing in the middle of a run.

**Comment by mexanick** [comment]
Was fixed in some PR to the master branch

**Comment by bdorney** [comment]
Closed by https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/140
