### ISSUE TITLE
Master branch is ahead of every other branch

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/vfatqc-python-scripts#151]
## Brief summary of issue

Master branch is ahead of every other branch. This shouldn't happen. The most recent version of the code should be in develop. Hot fixes should also branch off of develop. Master branch should be stable and get only PRs through develop. 
### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Shell used:

**Comment by jsturdy** [comment]
Actually, as per the model, hotfixes branch off of `master` and are back-ported to `develop` and other necessary feature branches

**Comment by bdorney** [comment]
Resolved by PR #158
