### ISSUE TITLE
Replace triple tab delimiter with single tab in all locations

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#16]
What is the purpose of using three tabs [here](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/master/MaskChannels.py#L114)
Do not use more delimiters than necessary

**Comment by gechen** [comment]
done.  @ReyerBand reduced the tabs from 3 to 1 [here](https://github.com/gechen/vfatqc-python-scripts/blob/master/MaskChannels.py#L114).
