### ISSUE TITLE
Structure of RPM package

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#160]
### Information
* The packages and modules will be packaged and end up in the system `PYTHONPATH`, e.g., (default `python` on `cc7):  `/usr/lib/python2.7/site-packages/`
  * I've been toying with adding a global namespace `gempython`, under which there would be the `gemplotting`, `vftaqc`, etc., modules, but this is still to be finalized into a proposal, and then discussed
  * This would necessarily involve a small redesign of the `import` statements, but I have for the most part decided on a workable solution for people who are doing private development and **not** using the production software
* Executable scripts, e.g., `amc_info_uhal.py` will **all** go into `/opt/cmsgemos/bin`, to make it simple to add this to the `PATH` variable and have the script ready

#### Current RPM structure
```
gempython_vfatqc          /opt/cmsgemos/bin/confAllChambers.py
gempython_vfatqc          /opt/cmsgemos/bin/confChamber.py
gempython_vfatqc          /opt/cmsgemos/bin/fastLatency.py
gempython_vfatqc          /opt/cmsgemos/bin/run_scans.py
gempython_vfatqc          /opt/cmsgemos/bin/trimChamber.py
gempython_vfatqc          /opt/cmsgemos/bin/ultraLatency.py
gempython_vfatqc          /opt/cmsgemos/bin/ultraScurve.py
gempython_vfatqc          /opt/cmsgemos/bin/ultraThreshold.py
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/__init__.py
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/__init__.pyc
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/__init__.pyo
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/__init__.py
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/__init__.pyc
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/__init__.pyo
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/macros/__init__.py
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/macros/__init__.pyc
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/macros/__init__.pyo
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/macros/longChannelMap.txt
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/macros/makeCompTable.py
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/macros/makeCompTable.pyc
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/macros/makeCompTable.pyo
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/macros/shortChannelMap.txt
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython/vfatqc/requirements.txt
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython_vfatqc-0.3.1-py2.7.egg-info/PKG-INFO
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython_vfatqc-0.3.1-py2.7.egg-info/SOURCES.txt
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython_vfatqc-0.3.1-py2.7.egg-info/dependency_links.txt
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython_vfatqc-0.3.1-py2.7.egg-info/not-zip-safe
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython_vfatqc-0.3.1-py2.7.egg-info/requires.txt
gempython_vfatqc          /usr/lib/python2.7/site-packages/gempython_vfatqc-0.3.1-py2.7.egg-info/top_level.txt
```

#### Current tarball structure
```
gempython_vfatqc-0.3.1/
gempython_vfatqc-0.3.1/gempython/
gempython_vfatqc-0.3.1/gempython/vfatqc/
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/confAllChambers.py
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/confChamber.py
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/fastLatency.py
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/run_scans.py
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/trimChamber.py
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/ultraLatency.py
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/ultraScurve.py
gempython_vfatqc-0.3.1/gempython/vfatqc/bin/ultraThreshold.py
gempython_vfatqc-0.3.1/gempython/vfatqc/macros/
gempython_vfatqc-0.3.1/gempython/vfatqc/macros/__init__.py
gempython_vfatqc-0.3.1/gempython/vfatqc/macros/longChannelMap.txt
gempython_vfatqc-0.3.1/gempython/vfatqc/macros/makeCompTable.py
gempython_vfatqc-0.3.1/gempython/vfatqc/macros/shortChannelMap.txt
gempython_vfatqc-0.3.1/gempython/vfatqc/__init__.py
gempython_vfatqc-0.3.1/gempython/vfatqc/requirements.txt
gempython_vfatqc-0.3.1/gempython/__init__.py
gempython_vfatqc-0.3.1/gempython_vfatqc.egg-info/
gempython_vfatqc-0.3.1/gempython_vfatqc.egg-info/PKG-INFO
gempython_vfatqc-0.3.1/gempython_vfatqc.egg-info/SOURCES.txt
gempython_vfatqc-0.3.1/gempython_vfatqc.egg-info/dependency_links.txt
gempython_vfatqc-0.3.1/gempython_vfatqc.egg-info/not-zip-safe
gempython_vfatqc-0.3.1/gempython_vfatqc.egg-info/requires.txt
gempython_vfatqc-0.3.1/gempython_vfatqc.egg-info/top_level.txt
gempython_vfatqc-0.3.1/README.md
gempython_vfatqc-0.3.1/setup.cfg
gempython_vfatqc-0.3.1/setup.py
gempython_vfatqc-0.3.1/PKG-INFO
```

**Comment by jsturdy** [comment]
Are the files in `macros` expected to be `import`ed?  Or are they expected to be run as scripts?

**Comment by bdorney** [comment]
> Are the files in `macros` expected to be `import`ed? Or are they expected to be run as scripts?

Where are you referring to?  Maybe this was a question for `gem-plotting-tools`?

**Comment by bdorney** [comment]
In the RPM structure above how are you handling: `$GEM_PLOTTING_PROJECT/mapping/chamberInfo.py`

Both `confAllChambers.py` and `run_scans.py` require the dictionaries that are defined and filled in this file.  Additionally, it is expected that the user is able to change the contents of those dictionaries.  While this will most likely not occur often for P5 in the present setup of the software it will most certainly be changing for QC8.

**Comment by jsturdy** [comment]
OK, right, have to be careful in my PR, as `macros` was still hanging around locally, because of untracked files.

**Comment by jsturdy** [comment]
Handling of the `import`s will be done with pythonic imports, e.g.,
```python
import gempython.gemplotting as gemplotting
from gemplotting import mapping.chamberInfo
```
or the like (this is the current baseline I'm testing from).

This specific file (and others which would be user-modifiable) could also be defined as "data", which could then go in a `/opt/cmsgemos/share/python` location, which *could* be added to the `PYTHON_PATH`, which could then be made editable by some group.  While not strictly "pythonic", neither is editing the python modules themselves... so should really be considered a "configuration" file, I guess.

**Comment by bdorney** [comment]
> This specific file (and others which would be user-modifiable) could also be defined as "data", which could then go in a /opt/cmsgemos/share/python location, which could be added to the PYTHON_PATH, which could then be made editable by some group. While not strictly "pythonic", neither is editing the python modules themselves... so should really be considered a "configuration" file, I guess.

To stay pythonic we could make a module take an input from a text file to at runtime set the correct settings in the dictionaries defined in `$GEM_PLOTTING_PROJECT/mapping/chamberInfo.py`.  Although this method would need to be run for scripts in both the `vfatqc-python-scripts` and also the `gem-plotting-tools` project.

Although in light of this refactoring we should consider how we configure from a `DB` or the `GEM DB`.  

Please advise.
