### ISSUE TITLE
Improvements to setTRIMDAC_and_Mask.py

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#17]
* Addition to this script of the final threshold scan and setting the value obtained to the VFAT threshold
  * Can do it per VFAT for now, and then use the ULTRA module in the future to do it for all VFATs simultaneously
* Addition of specification from command line of input file (if not specified, default should be the current behaviour)

**Comment by cbravo135** [comment]
This is already taken care of with the new configuration tools.

**Comment by jsturdy** [comment]
Obsoleted by a number of improvements
