### ISSUE TITLE
Add VFAT Mask to Command Line Options Parser

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#18]
Can we add a command line interface for the VFAT mask for the options parser in all python scripts in this package?

e.g. 

python2.7 pythonScript.py -s9 -g0 -vfatmask 7FFFFF

**Comment by jsturdy** [comment]
What do you see as the purpose of ```vfatmask```?

**Comment by bdorney** [comment]
Ideally in this script (or others) we could use vfatmask to choose which VFAT's the script would consider.

i.e. if someone wanted to run the S-Curve routine on VFATs 0-7, 9-23 they could use "vfatmask" to mask vfat 8.

**Comment by jsturdy** [comment]
* Migrate common settings to a gempythonoptions package (name to be decided)
  * Provide import interface for this package 
  * Provide sanity checks on all parameter options
* New requested option ```--vfats``` should be a string e.g., ```./script.py --vfats 1,3,5-9,23``` which would be parsed and ```script.py``` would be run for the selected VFATs.
  * If the option is not specified, and the script expects it, the default should be to run over all VFATs

**Comment by cbravo135** [comment]
Is this still relevant?

**Comment by bdorney** [comment]
I could see it being beneficial during future QC8 activities, so I'd say "yes"

**Comment by jsturdy** [comment]
Related to #70

**Comment by bdorney** [comment]
Would also suggest that masked VFATs are skipped in python scan routines (e.g. ultra*.py scripts).  

For example when running on the setup in the cosmic stand (6 VFAT positions unreachable):

[GE11COSMICS@cosmicstandtif 20170616]$ /home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/ultraThreshold.py -s2 -g0 --shelf=3 --perchannel 2>&1 | tee runlog_thresh_trigData.txt
2017.06.16.15.00
Channel #0
GEM_AMC.OH.OH0.ScanController.ULTRA
FW scan mode       : 1
FW scan min        : 0
FW scan max        : 254
Ultra FW scan mask : 0x00f40400
FW scan channel    : 0
FW scan step size  : 1
FW scan n_triggers : 1000
FW scan status     : 0x00000000
No handlers could be found for logger "gempython.tools.vfat_user_functions_uhal"
An exception occurred gem.shelf03.amc02.optohybrid00: error on VFAT transaction (chip 10, ContReg3)

Adding:

            if (mask >> i) & 0x1: continue

In appropriate positions fixes the above exception (done on user account of cosmic stand PC).

**Comment by bdorney** [comment]
Would also suggest in anaUltraThreshold.py to make the vt1 list a dict instead and then have the key value be the VFAT position.  See for example the implementation on the user account of the cosmic stand.
