### ISSUE TITLE
NameError: global name 'setTriggerThrottle' is not defined

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#19]
After sourcing paths:

source $BUILD_HOME/cmsgemos/setup/paths.sh

Then executing:

[GE11COSMICS@cosmicstandtif TOP]$ python2.7 /home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/pythonScript.py -s12 -g0
Start time: 01.12.2016-05.47.41.581448
Running A,B,C,D,E,F,G,H on AMC12  OH00
A. Testing the GLIB's presence
   Trying to read the GLIB board ID... If this test fails, the script will stop.
   > Passed... 

B. Testing the OH's presence
   Trying to set the OptoHybrid registers... If this test fails, the script will stop.
Traceback (most recent call last):
  File "/home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/pythonScript.py", line 109, in <module>
    testSuite.runSelectedTests()
  File "/home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/GEMDAQTestSuite.py", line 569, in runSelectedTests
    self.OptoHybridPresenceTest()
  File "/home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/GEMDAQTestSuite.py", line 139, in OptoHybridPresenceTest
    setTriggerThrottle(self.glib, self.gtx, 0)
NameError: global name 'setTriggerThrottle' is not defined

Have an error "setTriggerThrottle" is not defined.

For now we are rolling back from "tag-v1.0.2" to "master-reyer"

**Comment by jsturdy** [comment]
We will update the documentation, and provide a script so that in the future you will not have to run any of the scripts with the interpreter (having to try to guess which python version to use), they are executable and will be in the ```$PATH```
I tested this in 904 and do not see the error that you have, have requested a further test in the TIF

**Comment by jsturdy** [comment]
Just tested in the TIF and do not have this issue...
I suspect a mismatch between software tags
```v1.0.2``` of ```vfatqc-python-scripts``` requries ```v0.3.0``` or later of ```cmsgemos```
If you can replicate, please reopen, but closing for now, and making a note to make the readme clear
