### ISSUE TITLE
trimChamberV3.py Should Use nonlinear ARM DAC Calibration Curve

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#223]
## Brief summary of issue

See discussion at: https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/184

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

ARM DAC calibration should be changed from linear to nonlinear function:

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/2f5380c7fd3846dd1f2f3179476a4ea553e1ba0a/trimChamberV3.py#L69-L72

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/2f5380c7fd3846dd1f2f3179476a4ea553e1ba0a/trimChamberV3.py#L261-L271

## Current Behavior

Presently arm dac cal is linear.

## Context (for feature requests)

See discussion at: https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/184

## Your Environment

* Version used: 2f5380c7fd3846dd1f2f3179476a4ea553e1ba0a

**Comment by bdorney** [comment]
@AndrewLevin do you think you could implement this after the solution to cms-gem-daq-project/gem-plotting-tools#184 is approved?

**Comment by AndrewLevin** [comment]
Yes.

**Comment by bdorney** [comment]
@AndrewLevin now that the PR to gem-plotting-tools was merged can you update the function used in `trimChamberV3.py`

**Comment by AndrewLevin** [comment]
yes

**Comment by AndrewLevin** [comment]
Currently, `trimChamberV3.py` constructs the linear fit function from the slope and the intercept written to a text file. Should I change the text file to include all five parameters of the quartic polynomial or should I just import the function directly from the root file e.g. `calFile_CFG_THR_ARM_DAC_GE11-X-L-CERN-0002.root`?

**Comment by bdorney** [comment]
I think there are pro's and con's to both approaches.  For loading the function from the `TF1` object stored in the `TFile` this would allow us to change the function at a later date without changing `trimChamberV3.py` (definite *pro*).

However once upon a time I envisioned parameters like calibration constants would come from a DB interaction rather then text/root files located on the local file system.  So loading the function from a `TF1` might not be advantageous since I suspect calibration info would only be stored as a set of calibration constants (`float`'s in the DB) and not as a `TFile`.

I would suggest the following:

- Check if a `TFile` (following location/naming conventions) exists, 
- If file above exists load function from `TFile`,
- If the `TFile` does not exist parse a text file, of the expected format, and use this to create the calibration function

We expect both the `TFile` and the text file to exist since they are made at the same time; but the final bullet point here could be seen as a placeholder for a future DB interaction that retrieves the calibration constants and so the machinery to create a fit function would be needed anyway.

@mexanick and @jsturdy what do you think of @AndrewLevin's question and the proposed solution?

**Comment by bdorney** [comment]
@AndrewLevin can you implement the above and prepare a pull request by Friday evening?  We will need this update for the camp next week.

**Comment by AndrewLevin** [comment]
yes, what you wrote implies that I should eliminate the `calFileARM` option, right?

**Comment by bdorney** [comment]
> yes, what you wrote implies that I should eliminate the `calFileARM` option, right?

I would suggest to keep the option, default it to `None`.  If `calFileARM` is `None` then the procedure looks for the calibration file in the appropriate location (e.g. `$DATA_PATH/<detector_name>`).  If `calFileARM` is not `None` then the user input is used.

This provides the maximum flexibility.

**Comment by AndrewLevin** [comment]
ok, should I reserve time on the coffin to test this?

**Comment by bdorney** [comment]
> ok, should I reserve time on the coffin to test this?

Coffin is probably not the best since the ARM DAC calibration isn't "good."  I think you should use QC8, see discussion [here](https://mattermost.web.cern.ch/cms-gem-daq/pl/1exwce17db8u3yxj59xognnhoo)

**Comment by AndrewLevin** [comment]
please see this related pull request to gem-plotting-tools: https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/200

**Comment by AndrewLevin** [comment]
I noticed in this line https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/rpc-playground/trimChamberV3.py#L335 that the the `TGraph`, not the `TF1` is being evaluated. Presumably, this is a bug, since otherwise the "TrimDAC_vs_scurveMean" `TF1` is not used anywhere.

**Comment by bdorney** [comment]
> I noticed in this line https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/rpc-playground/trimChamberV3.py#L335 that the the `TGraph`, not the `TF1` is being evaluated. Presumably, this is a bug, since otherwise the "TrimDAC_vs_scurveMean" `TF1` is not used anywhere.

Yeah this is not ideal, but it does *work* since the DAC is pretty linear and it's doing an interpolation between the points, see [TGraph::Eval](https://root.cern.ch/doc/master/classTGraph.html#ab33753b0102ae87f91274cf277baa39b).

But while you're testing things it's probably better to use the actual `TF1`.

Thanks for catching this.

**Comment by bdorney** [comment]
Addressed by #250
