### ISSUE TITLE
[Feature Request] Include Trigger Link Check in testConnectivity.py

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#224]
## Brief summary of issue

Right now the connectivity testing is only checking the GBT paths between the backend and frontend electronics.  There is no check of the health of the trigger links.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

I think a step should be added between Step 3, Programming FPGA, and Step 4, GBT Phase Scans, that checks trigger link status is good.  An example of a good link status is shown [here](https://github.com/cms-gem-daq-project/sw_utils/blob/develop/v3ElectronicsUserGuide.md#checking-trigger-link-status).

This can be implemented by exposing [getmonTRIGGEROHmainLocal(...)](https://github.com/cms-gem-daq-project/ctp7_modules/blob/f6904b53c70f5189248d3fd0d02d558bec2ddfa6/src/daq_monitor.cpp#L84-L133) to the python API.  To do this, for the short term, an xhal interface to the remote callable version of the local function [getmonTRIGGEROHmain(...)](https://github.com/cms-gem-daq-project/ctp7_modules/blob/f6904b53c70f5189248d3fd0d02d558bec2ddfa6/src/daq_monitor.cpp#L135-L163) should be provided in the `legacyPreBoost` branch of `xhal`.  This would then need to be added to the the `HwAMC` class in `gempython`.

### Concerns for Only QC7

When working with detectors in some other test stand (e.g. coffin, QC8, sustained operation, etc...) we will only care about the GEM trigger link.

For QC7 we want to check that both the GEM trigger link (in the MTP12 connector panel) and the CSC trigger link (separate LC duplex connector on patch panel).  The way to do this would be for OHN to have the GEM trigger link going to OHN and the CSC trigger link going to OHN+1 on the fiber patch panel.  Then the code should check for a given OH that OHN and OHN+1 have the good status.  Here the provided `ohMask` with respect to the trigger should be treated as a even bits corresponding to OHN and odd bits corresponding to the CSC trigger link of OHN.

This behavior should only be checked if a given flag is provided, e.g. `--checkCSCTrigLink`.  Otherwise OHN should only correspond to OHN trigger link and the code should respect the given `ohMask`.

## Current Behavior

No check of the trigger link status is presently performed.

## Context (for feature requests)

Need a way to check the health of the trigger links before the superchamber is closed.

## Your Environment

* Version used: d38b9746bad1ccbdd4056c2406c15dd0055def7c

**Comment by bdorney** [comment]
@BenjaminRS this is needed by mid-march.

**Comment by jsturdy** [comment]
Closed by #232
