### ISSUE TITLE
Bug Report: connectivity testing issue

### ISSUE THREAD

**Issue by ChristosRos** [cms-gem-daq-project/vfatqc-python-scripts#226]
We are trying to perform a connectivity test. It seems that there is an issue with OH11. 
For this reason we want to skip some steps in order to pinpoint the exact problem. Therefore we use: 
testConnectivity.py -d -i -m 5 -n 200 -o 0x800 --shelf=1 --slot=4 --skipDACScan --skipScurve -f5 2>&1 | tee connectivityLog_n200.log

### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior
Normally we expect to have an output the connectivity status of the OH and the phases of the VFATs
## Current Behavior
testConnectivity.py -d -i -m 5 -n 200 -o 0x800 --shelf=1 --slot=4 --skipDACScan --skipScurve -f5 2>&1 | tee connectivityLog_n200.log
Sorry but you're asking me to skip all initial steps and all follow-up steps
This doesn't make sense; please reconsider

### Steps to Reproduce (for bugs)

1. Log in to gem904qc8daq pC 
2. Open a screen 
3. Run the command: testConnectivity.py -d -i -m 5 -n 200 -o 0x800 --shelf=1 --slot=4 --skipDACScan --skipScurve -f5 2>&1 | tee connectivityLog_n200.log

## Your Environment

* Version used:
* Shell used:

**Comment by bdorney** [comment]
Problem is here:

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/d38b9746bad1ccbdd4056c2406c15dd0055def7c/testConnectivity.py#L822-L826

Line 822 should here `args.firstStep > 4` should be changed to `args.firstStep > 5`.

**Comment by bdorney** [comment]
Closed by #227
