### ISSUE TITLE
[feature request]: testConnectivity.py does full scurve analysis.

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#244]
## Brief summary of issue

See title.  Implement a call of `anaUltraScurve.py` in `anaScurve`:

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0691c4ced7804d40bd1b735dcebb8e0f5700f505/testConnectivity.py#L26-L58

The easiest would be to use the `runCommand` wrapper. 

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

Full scurve results are produced.

## Current Behavior

Right now the number of dead channels is determined but there's no way to evaluate this number since there's no other output.  The raw data of course could be re-analyzed but might as well do that in the original call.

## Context (for feature requests)

Not possible to evaluate the number of dead channels reported by the very end of the routine without seeing the full data.

## Your Environment

* Version used:
* Shell used:

**Comment by lpetre-ulb** [comment]
New features won't be implemented in legacy. The QC7 procedure works fine without this change, even if it could bring limited speed up.
