### ISSUE TITLE
[Bug Report] testConnectivity.py reports success if scurve fails

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#246]
## Brief summary of issue

If the scurve fails to be taken the fitting algorithm does not find any dead channels (they are all fit failed) and then the routine reports that the connectivity testing has passed when it certainly hasn't.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Procedure should raise an error or somehow alert the user that a problem has occurred instead of continuing on.

## Current Behavior

http://cmsonline.cern.ch/cms-elog/1082262

### Steps to Reproduce (for bugs)

See above elog.

## Possible Solution (for bugs)

I think a check on the size of the `TFile` created by the scurve would be possibly sufficient.  A successful scurve would have a size around 2MB.  While a failed curve would be measured in kB.

## Context (for feature requests)

QC7 doesn't succeed successfully.

## Your Environment

* Version used:
* Shell used:

**Comment by lpetre-ulb** [comment]
As stated in #244, a complete Scurve analysis will never be performed in `testConnectivity.py` with the legacy software.
