### ISSUE TITLE
In an attempt to take s-curves, I used confAllChambers.py and it got stuck, twice. The third attempt was successful.

### ISSUE THREAD

**Issue by kithsirimalagalage** [cms-gem-daq-project/vfatqc-python-scripts#247]
## Brief summary of issue
In gemuser@gem904qc8daq, attached to the screen Scurve_D, I gave the following command:
[gemuser@gem904qc8daq ~]$ confAllChambers.py --shelf=1 --run --config 2>&1 | tee connectivityLog09042019.log

It gave the usual messages about mismatches, configuring VFTA registers etc., and was stuck for nearly an hour at a stage at the stage 

.....
Initial value to write: 33, register GEM_AMC.OH.OH3.GEB.VFAT9.CFG_THR_ARM_DAC
Set link 3 VFAT10 CFG_THR_ARM_DAC to 25
Initial value to write: 25, register GETTree::SetCacheSizeAux:0: RuntimeWarning: A TTreeCache could not be created because the TTree has no file
TTree::SetCacheSizeAux:0: RuntimeWarning: A TTreeCache could not be created because the TTree has no file
TTree::SetCacheSizeAux:0: RuntimeWarning: A TTreeCache could not be created because the TTree has no file

So I killed it with control C and restarted. This time it started with some error messages, and then continued as usual, as follows, but again got stuck. 

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 376, in _handle_results
    task = get()
TypeError: ('__init__() takes exactly 3 arguments (2 given)', <class 'gempython.tools.optohybrid_user_functions_xhal.OHRPCException'>, ('broadcastWrite failed for device 0; reg: CFG_RUN; with mask 8',))

TTree::SetCacheSizeAux:0: RuntimeWarning: A TTreeCache could not be created because the TTree has no file
TTree::SetCacheSizeAux:0: RuntimeWarning: A TTreeCache could not be created because the TTree has no file
TTree::SetCacheSizeAux:0: RuntimeWarning: A TTreeCache could not be created because the TTree has no file
Open pickled address table if available  /opt/cmsgemos/etc/maps//amc_address_table_top.pickle...
Initializing AMC gem-shelf01-amc04
Configuring VFATs on (shelf1, slot4, OH6) with chamber_vfatDACSettings dictionary values
biased VFATs on (shelf1, slot4, OH6)
Set CFG_THR_ARM_DAC to 100
VFATs on (shelf1, slot4, OH6) set to run mode
Configuring Channel Registers on (shelf1, slot4, OH6) based on /data/bigdisk/GEM-Data-Taking/GE11_QC8//configs/chConfig_GE11-X-S-INDIA-0007.txt
Comparing Currently Stored Channel Registers on (shelf1, slot4, OH6) with /data/bigdisk/GEM-Data-Taking/GE11_QC8//configs/chConfig_GE11-X-S-INDIA-0007.txt

It was killed with ctrl-c for the second time and the same command was executed for a third time. Then it was executed successfully within a few seconds.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior
The command 
confAllChambers.py --shelf=1 --run --config 2>&1 | tee connectivityLog09042019.log
should be executed within a few seconds and the results should be written in the specified log file.
## Current Behavior
Most of the time it behaves as expected. But at this particular time, it got stuck twice, and worked correctly at the third attempt. It may be related to some QC7 script being executed at the same time.

### Steps to Reproduce (for bugs)
One can attempt to reproduce it with:
[gemuser@gem904qc8daq ~]$ confAllChambers.py --shelf=1 --run --config 2>&1 | tee connectivityLog09042019.log

## Your Environment

I was working as gemuser on gem904qc8daq.cern.ch

**Comment by bdorney** [comment]
Seems like a syntax error here:

```bash
Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
self.run()
File "/usr/lib64/python2.7/threading.py", line 765, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/lib64/python2.7/multiprocessing/pool.py", line 376, in _handle_results
task = get()
TypeError: ('init() takes exactly 3 arguments (2 given)', <class 'gempython.tools.optohybrid_user_functions_xhal.OHRPCException'>, ('broadcastWrite failed for device 0; reg: CFG_RUN; with mask 8',))
```

**Comment by lpetre-ulb** [comment]
AFAIK, `confAllChambers.py` is frequently used at QC8 with success. There was a fix at some point (can't find the exact PR) which restored the script functionalities. Feel free to reopen if the issue still exists.
