### ISSUE TITLE
Additional diagnostic for GBT Phase scan failure

### ISSUE THREAD

**Issue by mmaggi** [cms-gem-daq-project/vfatqc-python-scripts#252]
## Brief summary of issue
During the connectivity test in case of failure additional diagnostic would be useful

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

In the python script the VFAT is declared bad in case the GBT phase is not determined and there 
are several possibilities. It would be useful to know in which category of failure the VFAT is.

## Current Behavior

The connectivity test simply claim a failure. 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context (for feature requests)

The additional diagnostic allows the operator to gain better experience of the problem encountered and the effectiveness of solution suggested

## Your Environment

* Version used:
* Shell used:

**Comment by jsturdy** [comment]
Can you provide some phase scan data (or example case) that results in a failure that you would like to have information printed about?
As stated, this issue provides insufficient information.

**Comment by bdorney** [comment]
Closing as stale; and based on QC7/8 this issue is no longer relevant.
