### ISSUE TITLE
[(Last) Feature Request] rpc-playground: Switch ultraScurve.py and ultraThreshold.py to use genChannelScan

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#255]
## Brief summary of issue

Right now `ultraScurve.py` and `ultraThreshold.py` launch one RPC call per channel being scanned with the `VFAT_DAQ_MONITOR`.  The time per scan could be significantly reduced by reducing the number of RPC calls per channel.  This can be achieved by passing `-1` to `HwOptohybrid::performCalibrationScan(...)` method:

https://github.com/cms-gem-daq-project/cmsgemos/blob/b1f547884776dabf59f25792c31b64fdcc7ae992/gempython/tools/optohybrid_user_functions_xhal.py#L430-L433

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] (Last) Feature request (request for change which adds functionality)

## Expected Behavior

I'll outline the case for `ultraScurve.py`.  The case for `ultraThreshold.py` would then be almost identical.

Change these lines:

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/31bf169cd52330decb1915d4182650f9a907330d/ultraScurve.py#L22-L25

To be a single input argument, say `--chanRange` which takes two comma separated numbers and defaults to `None`.  If a range is supplied by the user then the current algorithm is used.  If this parameter is left as `None` then we do the following, e.g.

```python
if options.chanRange is not None:
   # Do the current algorithm
else:
   # Do new algorithm
```

The definition of the array used to store the results of the RPC call:

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/31bf169cd52330decb1915d4182650f9a907330d/ultraScurve.py#L150-L152

Would be shifted inside the if statement above, the current lines would be placed under the current algorithm spot and then the lines would be repeated under the else block with an additional multiplier of 128 to increase the array size to handle all channels.

The new algorithm would basically take these lines:

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/31bf169cd52330decb1915d4182650f9a907330d/ultraScurve.py#L161-L178

And change `chan` argument to `-1`.

Then when filling the output TTree:

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/31bf169cd52330decb1915d4182650f9a907330d/ultraScurve.py#L180-L223

We would insert the loop over channels and this should match the indexing in the corresponding `ctp7_modules` [genChannelScan(...)](https://github.com/cms-gem-daq-project/ctp7_modules/blob/b358ed18fd77ed0625b5f04082df7d19da2d7ff6/src/calibration_routines.cpp#L1326-L1330) reported below for convenience:

```C++
    uint32_t outData[128*24*(dacMax-dacMin+1)/dacStep];
    for (uint32_t ch = 0; ch < 128; ch++) {
        genScanLocal(&la, &(outData[ch*24*(dacMax-dacMin+1)/dacStep]), ohN, mask, ch, useCalPulse, currentPulse, calScaleFactor, nevts, dacMin, dacMax, dacStep, scanReg, useUltra, useExtTrig);
    }
    response->set_word_array("data",outData,24*128*(dacMax-dacMin+1)/dacStep);
```

This should then work without too much issue and decrease the total number of RPC calls.  The only draw back would be that the user wouldn't see any terminal output until the scan completed.

## Current Behavior

There is one RPC call per channel which increases the total scan time.

## Context (for feature requests)

Decrease time required for calibration measurements.

**Comment by bdorney** [comment]
@jsturdy @mexanick I believe I'm supposed to submit an issue now before plowing ahead with feature development ;)

This is following up our software dev's meeting this morning.

**Comment by bdorney** [comment]
Okay after some preliminary investigation there's no real time difference between the two methods.

http://cmsonline.cern.ch/cms-elog/1083967

So we should investigate with @evka85 how long it would take to insert 12 `VFAT_DAQ_MONITOR` blocks into the FW and if this is justified once he returns from holiday.  Otherwise the only way to decrease calibration time would be to move to using the full tracking data path.

**Comment by lpetre-ulb** [comment]
No new features will be implemented in legacy. Moreover the proposed solution did not provide the expected gain in terms of scan during.
