### ISSUE TITLE
[feature request] Adapt for updated python bindings

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#263]
## Brief summary of issue
Need to update tools for use with new python bindings (cms-gem-daq-project/cmsgemos#289)
This work may well be broken into smaller pieces.
* Must also port and adapt current tools in the `RPC` branch

### Types of issue
- [x] Feature request (request for change which adds functionality)

## Expected Behavior
Tools should use new `cmsgemos_gempython` library

## Current Behavior
Current code uses old style `uhal` functionality which mimics old `cmsgemos` behaviour (and functionality in `RPC` branches adds `xhal`

## Dependencies
* cms-gem-daq-project/cmsgemos#289

**Comment by lpetre-ulb** [comment]
As for https://github.com/cms-gem-daq-project/cmsgemos/issues/289, obselete in terms of legacy. Will be re-opened on GitLab if needed.
