### ISSUE TITLE
Feature Request: Change testConnectivity.py To Use GBT Phase Look Up Table by Default 

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#270]
## Brief summary of issue

We lose a lot of time in QC7/QC8 during GBT phase scans; also users struggle to remember that an older QC7 run can be used to set the phases and that a new phase scan is generally not needed (e.g. QC7 is performed without cooling circuit; then LV is shut off and cooling circuit is added; phases from first QC7 can typically be used here).

For this I would propose that the default behavior would be to *not* do a GBT phase scan but instead apply the phase settings stored in the look-up table `vfat3GBTPhaseLookupTable` in [`hw_constants.py`](https://github.com/cms-gem-daq-project/cmsgemos/blob/generic-amc-RPC-v3-short-term/gempython/tools/hw_constants.py).

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

Change the `--skipGBTPhaseScan` argument to `--doGBTPhaseScan`.  Change step 4 to be such that if `--doGBTPhaseScan` is `False` we simply write the GBT phase settings from the LUT table.  If `--doGBTPhaseScan` is `True` then the current algorithm is used.

## Current Behavior

Unless specified we are always doing phase scan and this can take a lot of time (especially as the number of unmasked OH's increases)

## Context (for feature requests)

Quality of life plus decreased "can't do anything else" time during QC7/8.

## Your Environment

* Version used: dae6fb9a1d65f0d7081dc040832faf1c5f77123e
* Shell used:

**Comment by lpetre-ulb** [comment]
Would be interesting feature to some gain time, but a lot of information would be lost during the QC steps. Not worth being fixed in legacy.
