### ISSUE TITLE
Feature Request: Add TBranch to output TTree created by sbitRateScanAllLinks(...) to store Detector Serial Number

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#273]
## Brief summary of issue

Right now the data taken by function [`sbitRateScanAllLinks()`](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/rpc-playground/utils/scanUtils.py#L378-L566) contains multiple OH's but does not include the detector serial number in the output path.  This makes the risk that some later time this information could be lost.  Request to add a TBranch in the output file that stores this information.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

The `sbitRateScanAllLinks` would need to import `chamber_config` dictionary or take it as an input argument (as [`sbitRateAnalysis`](https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/9ce5139a7d9b1a657646e00b8753ea52807286c4/utils/threshAlgos.py#L1139-L1453) does).  This would provide the mapping of geographic address to chamber name.

Then the [`gemSbitRateTreeStructure`](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/15cf95544f2c2e0d98864ae8a65f166d80f9d245/utils/treeStructure.py#L213-L266) object would need a data member for storing chamber name and an associated `TBranch`.

This would then be filled at in `sbitRateAnalysis` at:

 - VFAT level: [L496-L506](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/15cf95544f2c2e0d98864ae8a65f166d80f9d245/utils/scanUtils.py#L496-L506)
 - Overall rate: [L525-L535](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/15cf95544f2c2e0d98864ae8a65f166d80f9d245/utils/scanUtils.py#L525-L535)

## Current Behavior

Detector serial number is not stored in output raw file.

## Context (for feature requests)

See above.

## Your Environment

* Version used: 15cf95544f2c2e0d98864ae8a65f166d80f9d245
* Shell used:

**Comment by bdorney** [comment]
This would then need a corresponding update to `anaSbitThresh.py` in the `gem-plotting-tools` repo to support this new TBranch.

**Comment by AndrewLevin** [comment]
I believe the same issue occurs for DAC scans, but possibly there was some reason why @bdorney made the issue only about sbit rate scans?

**Comment by jsturdy** [comment]
I would think this would be useful for *all* scan types in fact

**Comment by AndrewLevin** [comment]
Yes, I agree. I guess this implies that the `chamber_config` will be required for all scan types now, but that is a minor inconvenience.

**Comment by AndrewLevin** [comment]
> This would then need a corresponding update to `anaSbitThresh.py` in the `gem-plotting-tools` repo to support this new TBranch.

It is not clear to me what exactly "support this new TBranch" means. I would guess it means to use the contents of the new TBranch instead of the `chamber_config` to create the output directory. If there are no objections, I will implement that.

**Comment by jsturdy** [comment]
I might also think that anything that is printing a detector name on a plot somewhere, would use this, but probably this is all coming from some initial fetch from the `chamber_config`...
I think that on the analysis side, the `chamber_config` should be completely removed, since this information should come from the run metadata, but let's see how this shakes out

**Comment by AndrewLevin** [comment]
While we are adding a detector serial number branch, I would propose we also add a GEB type branch ("short" or "long") such that the analysis doesn't need any additional information about the detector.

**Comment by jsturdy** [comment]
If we are using the detector serial number, the type can be extracted from the name.
In a future world, the type could be extracted from the DB using the detector serial number.
As such, I would suggest the minimal change to the tree structure

**Comment by AndrewLevin** [comment]
There is currently a dictionary for the detector name

https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/develop/mapping/chamberInfo.py#L22-L24

and for the GEB type

https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/develop/mapping/chamberInfo.py#L33-L35

To me it seems you are right that the GEB type dictionary is unnecessary because the detector name will always contain -S- or -L-. So probably we can remove the GEB type dictionary and write a function that returns the GEB type based on the detector name.

**Comment by jsturdy** [comment]
This also depends on how the GE2/1 and ME0 detectors will be named (@mexanick or @sbutalla can comment)

**Comment by jsturdy** [comment]
Closed by #276
