### ISSUE TITLE
Feature Request: Add iterativeTrim.py to run_scans.py

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#274]
## Brief summary of issue

The `iterativeTrim.py` routine was added in https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/272.

For ease of use for the user this routine could be added to `run_scans.py` using the subcommand `iterTrim`.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

The `iterTrim` is an available subcommand in `run_scans.py`.  Functionality should work similarly to the subcommand `trimV3` with similar level of option support.

## Current Behavior

`iterativeTrim.py` is not part of `run_scans.py`

## Context (for feature requests)

Would help users to have this tool integrated in `run_scans.py` although the long term usability is dubious with the rise of the calibration suite in xdaq.

**Comment by AndrewLevin** [comment]
I have implemented this. Should I test it on the coffin?

**Comment by jsturdy** [comment]
> I have implemented this. Should I test it on the coffin?

Go ahead and make a booking

**Comment by jsturdy** [comment]
Closed by #275
