### ISSUE TITLE
First Draft at Sphinx documentation

### ISSUE THREAD

**Issue by vetens** [cms-gem-daq-project/vfatqc-python-scripts#278]
## Brief summary of issue

@jsturdy @mexanick 
 I have made a first draft of the sphinx documentation scaffolding, code present [here](https://github.com/vetens/vfatqc-python-scripts/tree/rpc-playground). 
Sphinx scaffolding added (update in makefiles, config files added), docstrings added to all tools referenced by `run_scans.py`. Templates for html can be found in the `*.rst` files in `doc/` and `doc/man/`.

Copies of the generated html can also be found at `/afs/cern.ch/user/w/wvetens/public/vfqchtml/`, just use your web browser of choice to open `index.html`.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

You should be able to just run `make doc` to produce the html

**Comment by mexanick** [comment]
@vetens could you please issue a pull request with a mark [WIP] (work in progress) so we can actually see the differences you've introduced? The github interface is quite nice for such things ;)

**Comment by vetens** [comment]
@mexanick Thanks for the tip! Pull request is here:
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/279

**Comment by mexanick** [comment]
Fixed in https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/279
