### ISSUE TITLE
Bug Report: testConnectivity.py Cntrl+c

### ISSUE THREAD

**Issue by bregnery** [cms-gem-daq-project/vfatqc-python-scripts#280]
testConnectivity.py does not cleanly quite upon recieveing the Cntrl+c command.

## Brief summary of issue
When testConnectivity.py receives the Cntrl+c command then it dumps out random information for 5 minutes.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior
Ideally this should cleanly quite rather than hijacking the screen for several minutes.

## Current Behavior
Dumps information

### Steps to Reproduce (for bugs)

1. start testConnectivity.py
2. quickly press Cntrl+c

## Your Environment

* Version used: 2.7.5
* Shell used: Bash

**Comment by lpetre-ulb** [comment]
If I correctly understand the issue, the output is the raw address table. This happens with all tools using the Pickle file. Won't be fixed in legacy. The trick is, if running into a `screen` or `tmux` session to detach from it. Most of the time is spent displaying the data, not dumping them out.
