### ISSUE TITLE
Trimming procedure improvement (3sigmas)

### ISSUE THREAD

**Issue by giovanni-mocellin** [cms-gem-daq-project/vfatqc-python-scripts#283]
With present trimming of channels at the scurve mean, threshold does not get reduced significantly. The alignment of the channels at mean-3sigmas (including the mod for channels that result to be not trimmable since already with trimDAC at +63) can lower the thresholds by 37%. Presentation link: https://indico.cern.ch/event/858083/contributions/3612748/attachments/1933349/3202898/TrimmingThresholdStudyInDepth_-_Giovanni_Mocellin_-_25-10-2019_-_v2.pdf
New feature requested to include this different trimming procedure.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

The trimming procedure should align the mean-3sigmas values, so the noise levels of the channels and not the 50% response of them.

## Current Behavior

Same as above.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context (for feature requests)

You can find the code example at gemuser in qc8daq machine in the folder home/Giovanni, filename "getTrimValuesFromScurve.py".

## Your Environment

qc8daq machine, private code

**Comment by AndrewLevin** [comment]
Hi Giovanni,

Sorry, I missed the offline and operations meeting because I am at a conference. I have a basic question: where does the noise level of 100 Hz come from? Have you checked whether it has any effect on the efficiency for the amount of charge deposited by a muon if you use 0 Hz, or the first zero point in sbitThresh plot, instead?

Andrew

**Comment by giovanni-mocellin** [comment]
Hi Andrew,

We choose to use that point because we can afford it: it is orders of magnitude lower than the background rate in CMS. Moreover, in the stand we basically so not see noise hits if we set that amount of noise. Going to 100Hz helps in reducing the threshold values - they are of course better than the 0Hz point...

Giovanni

**Comment by AndrewLevin** [comment]
Let me try to explain my point with an example: if the sbitThresh scan goes to 0 at THR_DAC = 20 and this corresponds to 1 fC, and muon always deposits between 2 and 3 fC, and this corresponds to THR_DAC = 30 to 40, then we can just set THR_DAC to 25 and get maximum efficiency and 0 noise. So, my point is that before we try to develop a complex algorithm to set the the threshold and the trim values, we should check whether we are in a situation where there is actually a tradeoff.

**Comment by giovanni-mocellin** [comment]
We are actually in a situation where we need to lower down the thresholds as much as we can and allowing a small amount of noise is a very good deal. In QC8 lately we were even using 10'000Hz and all was good. The numbers that you quote there are only ideal unfortunately... All this study was done to get better efficiency, and even, if possible, lowering the HV applied to reduce the discharges, but still keeping high efficiency. For HV & Efficiency we can have a compromise, but the threshold must be as low as possible.

**Comment by AndrewLevin** [comment]
> In QC8 lately we were even using 10'000Hz and all was good. 

So, did you actually do a test under the same conditions at 10'000Hz, 1000Hz, 100Hz, etc and plot the efficency as a function of noise rate? Are there slides about that somewhere?

**Comment by AndrewLevin** [comment]
@giovanni-mocellin , do you want to align the `mean - 3*sigma` values to the average of `mean - 3*sigma` over the VFAT or the average of `mean` over the VFAT?

**Comment by giovanni-mocellin** [comment]
I would suggest to go to mean-4*sigma: better results seen there. And we need to align the mean-4*sigmas to the avg of the mean-4*sigmas. Also we would need to have the so-called "mod63".

We can see this together today in the 904 lab.
