### ISSUE TITLE
testConnectivity.py fails to update the VFAT3 configuration files on the CTP7

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/vfatqc-python-scripts#291]
## Brief summary of issue

During commissioning at P5, @bregnery and @giovanni-mocellin reported an issue with `testConnectivity.py` not being able to properly update the VFAT3 configuration files on the CTP7 after successful DAC scans. This results in [incorrectly biased VFATs and empty Scurves](https://mattermost.web.cern.ch/cms-gem-ops/pl/ah3x4zpc8jfemyedyjtqe9r7wr).

They noticed [empty `NominalValues-*` files](https://mattermost.web.cern.ch/cms-gem-ops/pl/c5iosekktpyqprbwtfea95gipe) on the CTP7. No error message is reported, either in the `testConnectiviy.py` output or in the CTP7 logs.

The DAC scans output files *are* written in the right location in the `$DATA_PATH`. The issue only occurs for some chambers. Until now, this seems to only affect both chambers of `GEMINIm09`.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

The VFAT3 configuration files on the CTP7 should be updated after successful DAC scans in `testConnectivity.py`. An error should be reported in case of error.

## Current Behavior

`testConnectivity.py` *sometimes* fails to update the VFAT3 configuration files on the CTP7 without printing any error message.

### Steps to Reproduce (for bugs)

1. Launch `testConnectivity.py` with *some chambers*...
2. Look a the upload file size on the CTP7: `ls -lhtr /mnt/persistent/gemuser/NominalValues-*`

## Possible Solution (for bugs)

The issue can reliably be reproduced on the ULB setup which helped for investigations.

First, increase the verbosity of the `scp` call as well as decreasing its speed for better debuggability. In [`updateVFAT3ConfFilesOnAMC`](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0e4e89c67d2968085fa83403e7e5a2e874325af6/utils/confUtils.py#L447):

``` python
    # Copy Files
    copyFilesCmd = [
            'scp', '-v',
            filename,
            'gemuser@{0}:{1}'.format(cardName,gemuserHome)
            ]
    import sys, time
    time.sleep(1)
    runCommand(copyFilesCmd, log = sys.stdout)
```

The more verbose output of `testConnectivity.py` is interesting:

``` bash
[...]
debug1: Sending command: scp -v -t /mnt/persistent/gemuser/
Sending file modes: C0644 0 NominalValues-CFG_BIAS_PRE_VREF.txt
Sink: C0644 0 NominalValues-CFG_BIAS_PRE_VREF.txt
NominalValues-CFG_BIAS_PRE_VREF.txt                                                                                                        100%    0     0.0KB/s   00:00
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
[...]
```
(similar output for all `NominalValues-*` files)

The sent files have a size of 0! This is confirmed by `ls` *during the SSH calls*:

``` bash
(pyvenv) [lpetre@gem-daq ctp7_modules]$ ll -sh ~/data/data/GE11-TestStand10/dacScans/2020.01.14.20.14/
total 2.4M
1.3M -rw-r--r--. 1 lpetre lpetre 1.3M Jan 14 20:23 DACFitData.root
   0 -rw-r--r--. 1 lpetre lpetre    0 Jan 14 20:23 NominalValues-CFG_BIAS_CFD_DAC_1.txt
   0 -rw-r--r--. 1 lpetre lpetre    0 Jan 14 20:23 NominalValues-CFG_BIAS_CFD_DAC_2.txt
   0 -rw-r--r--. 1 lpetre lpetre    0 Jan 14 20:23 NominalValues-CFG_BIAS_PRE_I_BIT.txt
   0 -rw-r--r--. 1 lpetre lpetre    0 Jan 14 20:23 NominalValues-CFG_BIAS_PRE_I_BLCC.txt
   0 -rw-r--r--. 1 lpetre lpetre    0 Jan 14 20:23 NominalValues-CFG_BIAS_PRE_I_BSF.txt
[...]
```

Once `testConnectivity.py` returns, the files have the expected size:

``` bash
(pyvenv) [lpetre@gem-daq ctp7_modules]$ ll -sh ~/data/data/GE11-TestStand10/dacScans/2020.01.14.20.14/
total 2.6M
1.5M -rw-r--r--. 1 lpetre lpetre 1.5M Jan 14 20:23 DACFitData.root
4.0K -rw-r--r--. 1 lpetre lpetre  134 Jan 14 20:23 NominalValues-CFG_BIAS_CFD_DAC_1.txt
4.0K -rw-r--r--. 1 lpetre lpetre  134 Jan 14 20:23 NominalValues-CFG_BIAS_CFD_DAC_2.txt
4.0K -rw-r--r--. 1 lpetre lpetre  158 Jan 14 20:23 NominalValues-CFG_BIAS_PRE_I_BIT.txt
4.0K -rw-r--r--. 1 lpetre lpetre  134 Jan 14 20:23 NominalValues-CFG_BIAS_PRE_I_BLCC.txt
4.0K -rw-r--r--. 1 lpetre lpetre  134 Jan 14 20:23 NominalValues-CFG_BIAS_PRE_I_BSF.txt
4.0K -rw-r--r--. 1 lpetre lpetre  135 Jan 14 20:23 NominalValues-CFG_BIAS_PRE_VREF.txt
```

=> **Hypothesis**: the files are never closed nor flushed and the writes are all buffered. Since `testConnectivity.py` calls `scp` before closing the DAC scan output configuration files, `scp` reads out an empty file.

Let's try to confirm this hypothesis. One can close the files in [`dacAnalysis`](https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/bbc3e2531ac0c7c8b817768bc2f99f8dee9e9ab4/utils/anautilities.py#L433) as soon as they are no longer needed:

``` python
# Can probably write a nicer code for that...
for a in outputTxtFiles_dacVals.values():
    for b in a.values():
        b.close()
```

`scp` now sends a file with a size different from 0 :smiley::

``` bash
debug1: Sending command: scp -v -t /mnt/persistent/gemuser/
Sending file modes: C0644 135 NominalValues-CFG_BIAS_PRE_VREF.txt
Sink: C0644 135 NominalValues-CFG_BIAS_PRE_VREF.txt
NominalValues-CFG_BIAS_PRE_VREF.txt                                                                                                        100%  135   159.2KB/s   00:00
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
```

And the DAC scan output files have the same size reported by `ls` *at the time of the SSH calls*:

``` bash
(pyvenv) [lpetre@gem-daq ctp7_modules]$ ll -sh ~/data/data/GE11-TestStand10/dacScans/2020.01.14.20.24/
total 2.5M
1.3M -rw-r--r--. 1 lpetre lpetre 1.3M Jan 14 20:32 DACFitData.root
4.0K -rw-r--r--. 1 lpetre lpetre  134 Jan 14 20:32 NominalValues-CFG_BIAS_CFD_DAC_1.txt
4.0K -rw-r--r--. 1 lpetre lpetre  134 Jan 14 20:32 NominalValues-CFG_BIAS_CFD_DAC_2.txt
4.0K -rw-r--r--. 1 lpetre lpetre  158 Jan 14 20:32 NominalValues-CFG_BIAS_PRE_I_BIT.txt
4.0K -rw-r--r--. 1 lpetre lpetre  134 Jan 14 20:32 NominalValues-CFG_BIAS_PRE_I_BLCC.txt
4.0K -rw-r--r--. 1 lpetre lpetre  134 Jan 14 20:32 NominalValues-CFG_BIAS_PRE_I_BSF.txt
4.0K -rw-r--r--. 1 lpetre lpetre  135 Jan 14 20:32 NominalValues-CFG_BIAS_PRE_VREF.txt
4.0K -rw-r--r--. 1 lpetre lpetre  158 Jan 14 20:32 NominalValues-CFG_BIAS_SD_I_BDIFF.txt
[...]
```

The `NominalValues-*` files also have the right size on the CTP7:

``` bash
eagle63:~$ ll
-rw-r--r--    1 gemuser  1001           134 Jan 14 18:09 NominalValues-CFG_BIAS_CFD_DAC_1.txt
-rw-r--r--    1 gemuser  1001           134 Jan 14 18:09 NominalValues-CFG_BIAS_CFD_DAC_2.txt
-rw-r--r--    1 gemuser  1001           158 Jan 14 18:09 NominalValues-CFG_BIAS_PRE_I_BIT.txt
-rw-r--r--    1 gemuser  1001           134 Jan 14 18:09 NominalValues-CFG_BIAS_PRE_I_BLCC.txt
-rw-r--r--    1 gemuser  1001           134 Jan 14 18:09 NominalValues-CFG_BIAS_PRE_I_BSF.txt
[...]
``` 

If the hypothesis is confirmed at P5, I have no solid idea why it sometimes works, even less why it *ever* worked...

I believe this should be confirmed at P5 before drawing any conclusions. It is probably best to increase the verbosity of the output first and check the outputs for both a working chamber and a non-working. And then use the same procedure with the file close calls. 

## Your Environment

* Version used: commissioning DAQ machine at P5
* Version used: https://github.com/cms-gem-daq-project/vfatqc-python-scripts/commit/0e4e89c67d2968085fa83403e7e5a2e874325af6 and https://github.com/cms-gem-daq-project/gem-plotting-tools/commit/dbb0e53c380843fc00053b642229e2a3cafaad45 at ULB

**Comment by jsturdy** [comment]
The file access here is done in a rather non-pythonic way (it would probably be better to universally create a file object and pass this to `pandas.DataFrame.to_csv()`, though there is a caveat that the file ["should be opened with newline=’’, disabling universal newlines."](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html)

(An alternative to what I suggest below would be to simply add the `chunksize` parameter and set it to ensure that the file is flushed 
```
chunksize : int or None

    Rows to write at a time.
```
)

Here:
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0e4e89c67d2968085fa83403e7e5a2e874325af6/getCalInfoFromDB.py#L60-L69

and here:
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0e4e89c67d2968085fa83403e7e5a2e874325af6/getCalInfoFromDB.py#L72-L81

the filename is passed to the `to_csv` function directly, as nothing special is written at the top of these files.

Here:
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0e4e89c67d2968085fa83403e7e5a2e874325af6/getCalInfoFromDB.py#L84-L95

and here:
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0e4e89c67d2968085fa83403e7e5a2e874325af6/getCalInfoFromDB.py#L98-L109

a file object is first created to put in the header line, and then the filename is passed to `to_csv`

Changing *all* of these to something like:
```python
filename_blah = "here/is/my/filename.txt"
with open(filename_blah,'w',newline='') as f:
    f.write("vfatN/I:slope/F:intercept/F\n") ## if required
    dbInfo.to_csv( 
         path_or_buf=f, 
         sep="\t", 
         columns=['vfatN','cal_dacm','cal_dacb'], 
         header=False, 
         index=False, 
         mode='a') ## or 'w' if no special header is added
runCommand(["chmod", "g+rw", filename_blah]) ## though this line was added against recommendation log ago anyway
```
will ensure that the buffers are flushed.

Additionally, there is a potential for undefined behaviour, in that the subsequent block:
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0e4e89c67d2968085fa83403e7e5a2e874325af6/getCalInfoFromDB.py#L113-L122

implicitly depends on the block starting at
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0e4e89c67d2968085fa83403e7e5a2e874325af6/getCalInfoFromDB.py#L44

having been run (otherwise, the filename variables would be referenced before being defined)
I think in a previous issue, the behavour was stated that `write2CTP7` was a strict dependency of `write2File` (though having the ability to write some stored configuration from the DAQ PC to the CTP7, without a DB lookup, always seemed like a valid use case to me), so if this is the case, that block should move into the same scope


I don't know if it's related, but the files on the CTP7 in question have mostly the same size with the exception of `NominalValues-CFG_BIAS_CFD_DAC_1.txt`, and its content appears to be the `cat` of all the NominalValues` files along with some random other bits (though this may be a residual effect of the currently reported bug)

```
eagle34:~$ head -50 NominalValues-CFG_BIAS_CFD_DAC_1.txt 
NominalValues-CFG_BIAS_CFD_DAC_2.txt0000664001172300117230000000020613522301164017032 0ustar  gemusergemuser0   37
1       41
2       34
3       31
4       33
5       37
6       42
7       36
8       37
9       43
10      36
11      34
12      31
13      40
14      33
15      38
16      40
17      41
18      31
19      37
20      37
21      38
22      36
23      36
NominalValues-CFG_BIAS_PRE_I_BIT.txt0000664001172300117230000000023613522301164017145 0ustar  gemusergemuser0   206
1       209
2       207
3       208
4       210
5       216
6       220
7       203
8       225
9       222
10      220
11      209
12      226
13      216
14      222
15      229
16      213
17      229
18      217
19      215
20      217
21      217
22      215
23      225
NominalValues-CFG_BIAS_PRE_I_BLCC.txt0000664001172300117230000000020613522301164017227 0ustar  gemusergemuser0  21
1       20
```

**Comment by AndrewLevin** [comment]
@lpetre-ulb, I think there is no reason to try to confirm with a test p5, it is obvious to me that you found the bug.

**Comment by jsturdy** [comment]
> @lpetre-ulb, I think there is no reason to try to confirm with a test p5, it is obvious to me that you found the bug.

Agreed, and even if this is not the whole issue, you've uncovered some fundamental issues in the code that were just waiting for the right time to rear their ugly head.
It would probably be wise to audit all other places doing file I/O to ensure the buffers are flushed as soon as the writes are finished

**Comment by lpetre-ulb** [comment]
> @lpetre-ulb, I think there is no reason to try to confirm with a test p5, it is obvious to me that you found the bug.

Agreed, I just would have liked to understand why the script sometimes works.

> > @lpetre-ulb, I think there is no reason to try to confirm with a test p5, it is obvious to me that you found the bug.
> 
> Agreed, and even if this is not the whole issue, you've uncovered some fundamental issues in the code that were just waiting for the right time to rear their ugly head.
> It would probably be wise to audit all other places doing file I/O to ensure the buffers are flushed as soon as the writes are finished

Also agreed. I fear that it concerns most of the file I/O operations, from the CSV-like files to ROOT `TFile`s...

> The file access here is done in a rather non-pythonic way (it would probably be better to universally create a file object and pass this to `pandas.DataFrame.to_csv()`, though there is a caveat that the file ["should be opened with newline=’’, disabling universal newlines."](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html)

Yeah, for all the CSV-like files, I think we should use `pandas.DataFrame.to_csv()` and `pandas.read_csv()` instead of relying of custom non-fully conformant CSV writers/parsers. I would advocate to use a text file format compatible with the ROOT text `TTree` files.

> (An alternative to what I suggest below would be to simply add the `chunksize` parameter and set it to ensure that the file is flushed
> 
> ```
> chunksize : int or None
> 
>     Rows to write at a time.
> ```
> 
> )

I'm rather in favor of the other options. ;)

> Changing _all_ of these to something like:
> 
> ```python
> filename_blah = "here/is/my/filename.txt"
> with open(filename_blah,'w',newline='') as f:
>     f.write("vfatN/I:slope/F:intercept/F\n") ## if required
>     dbInfo.to_csv( 
>          path_or_buf=f, 
>          sep="\t", 
>          columns=['vfatN','cal_dacm','cal_dacb'], 
>          header=False, 
>          index=False, 
>          mode='a') ## or 'w' if no special header is added
> runCommand(["chmod", "g+rw", filename_blah]) ## though this line was added against recommendation log ago anyway
> ```
> 
> will ensure that the buffers are flushed.

:+1: Indeed, we should try to use the context managers as often as possible. They maybe do not interface well with PyROOT though.

> Additionally, there is a potential for undefined behaviour, in that the subsequent block:
> [...]
> I think in a previous issue, the behavour was stated that `write2CTP7` was a strict dependency of `write2File` (though having the ability to write some stored configuration from the DAQ PC to the CTP7, without a DB lookup, always seemed like a valid use case to me), so if this is the case, that block should move into the same scope

This is already taken care of by those lines:
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0e4e89c67d2968085fa83403e7e5a2e874325af6/getCalInfoFromDB.py#L14-L17

> I don't know if it's related, but the files on the CTP7 in question have mostly the same size with the exception of `NominalValues-CFG_BIAS_CFD_DAC_1.txt`, and its content appears to be the `cat` of all the NominalValues` files along with some random other bits (though this may be a residual effect of the currently reported bug)
> 
> ```
> eagle34:~$ head -50 NominalValues-CFG_BIAS_CFD_DAC_1.txt 
> NominalValues-CFG_BIAS_CFD_DAC_2.txt0000664001172300117230000000020613522301164017032 0ustar  gemusergemuser0   37
> 1       41
> [...]
> ```

I know @bregnery and @giovanni-mocellin launched the `testConnectivity.py` SSH calls by hand since they were not working automatically. Maybe an error slipped through?

**Comment by jsturdy** [comment]
@AndrewLevin can you take care of this?
We could possibly also avoid the append write for the special cases where we add the header line for eventual `TTree` compatibility if the `to_csv::header` can insert it in the correct format.

**Comment by AndrewLevin** [comment]
Yes, I will take care of it.
