### ISSUE TITLE
updateConf.py with option for trimming results

### ISSUE THREAD

**Issue by giovanni-mocellin** [cms-gem-daq-project/vfatqc-python-scripts#298]
## Brief summary of issue

The script updateConf.py is presently changing symlinks for scurves chConfig and sbitThreshold scans vfatConfig output files. It would be nice to have an option for trimming results.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

An option like "-t"  might be added to the script updateConf.py, having it change the chConfig symlinks in the "$DATA_PATH/configs" folder for the trimming output (last iteration).

## Current Behavior

One additional option.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context (for feature requests)

Ease the symlink change for chConfig coming from trimming procedure.

## Your Environment

* Version used:
* Shell used:

**Comment by lpetre-ulb** [comment]
This script is currently maintained in the [`sw_utils`](https://github.com/cms-gem-daq-project/sw_utils) which is (not yet) affected by the recent feature freeze policy in legacy branches. Note that, the files hosted in this Git repository could potentially be moved to `gem_ops` and a documentation/website repository in the near feature.

**Comment by lpetre-ulb** [comment]
If this feature is required for QC8 operations (how is it currently done?), please re-open the issue in the `sw_utils` repository. In any case, closing the issue here.

**Comment by giovanni-mocellin** [comment]
it is done creating the symlinks manually. it's not the end of the world if we continue like this. for p5 something more sophisticated need to be created either way...

**Comment by lpetre-ulb** [comment]
Okay, thanks for your prompt reply, @giovanni-mocellin. Indeed, the DAQ configuration in the new software (including p5) will be stored in a full-featured database system. All the required tools for configuration update and visualization will also be developed.
