### ISSUE TITLE
Update scripts to use new ULTRA OH scan module

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#5]
Scripts need to be updated to use the latest OH firmware module
* Bring in new ```register_mapping.dat``` file
* Remove any looping over VFATs
* Add looping over VFAT data instead

This is a short term (~ 1 day) task
The long term task will be to migrate the entire framework to ```uhal```

**Comment by cbravo135** [comment]
Didn't I make this irrelevant?

**Comment by cbravo135** [comment]
The framework is migrated fully to uhal now right??
