### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#63]
Need to add unit tests to be able to test the code without depending on fully running to catch as many syntax and logic errors as possible.

**Comment by mexanick** [comment]
Maybe I miss something, but what do you want to cover with unit tests here? To me, the basic functions, which certainly require unit testing coverage are the ones in registers_uhal.py, vfat_user_functions_uhal.py and optohybrid_user_functions_uhal.py, which are (at leas for now) in different repository. The scripts in this repository may be covered by integration tests, however I doubt they really require unit testing.

**Comment by mexanick** [comment]
Saying that, I fully support that we have to provide tests!

**Comment by jsturdy** [comment]
Basically, tests which don't require running the full scurve just to ensure that the logic and syntax have been applied correctly (options are parsed properly, etc.)
We've had a couple of post merge "oops" moments, which required a hotfix, so would prefer to be able to run a quick set of tests that don't require one to actually run a full test (debug maybe should always run a reduced version of the tool, limiting to a single channel or a few channels)

**Comment by bdorney** [comment]
Implemented travis CI so I think we can close this.  Reopen if otherwise.
