### ISSUE TITLE
Remove hardcoded locations

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#64]
There are some hardcoded locations [here](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/master/anaAllChambers.py#L9) and [here](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/master/anaAllChambers.py#L10), whose behaviour should be understood for the foreseen use cases.

**Comment by cbravo135** [comment]
We took care of this by now, right?

**Comment by jsturdy** [comment]
Is fully resolved with #71
