### ISSUE TITLE
Make configurable the chambers passed into the system running scripts

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#70]
* ```run_scans.py``` and ```confAllChambers.py``` should be able to run over an arbitrary set of chambers and not expect a specific configuration
 * This can be implemented by a command-line switch *or* a config file, linked to an expected location

**Comment by jsturdy** [comment]
* https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/master/confAllChambers.py#L42 should loop over a list of specified links
* https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/master/anaAllChambers.py#L34 should loop over a list of specified links
* https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/master/run_scans.py#L156 and following should be constructed using only a list of specified links

**Comment by jsturdy** [comment]
Referenced by #71

**Comment by cbravo135** [comment]
I guess this is done now? The way you did it didn't seem like the full feature you were looking for?

**Comment by jsturdy** [comment]
Yeah, it's a stop-gap solution, requiring only one change, but still not necessarily the "best" solution

**Comment by bdorney** [comment]
It seems that the "stop-gap" solution has gone on for ~3 months.  I suggest we close this issue since above line numbers no longer appear relevant.
