### ISSUE TITLE
Analyzed SCurve Tree Format

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/vfatqc-python-scripts#74]
Understood that the TBranch "Chi2" is set via TF1::GetChisquare()

Suggest to change this to normalized chi2, e.g.:

TF1::GetChisquare() / TF1::GetNDF()

Also suggest to change the TBranch name to "normChi2" to match the calculation.

**Comment by jsturdy** [comment]
Better would be to add a new branch ```ndf```, if the reduced chi2 is wanted in further analysis

**Comment by jsturdy** [comment]
Added in #75
