### ISSUE TITLE
Multiple subprocess.call invocation in python-only routines

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/vfatqc-python-scripts#78]
Is there a good reason to invoke subprocess.call every time we need to run another python script?
Example: confAllChambers.py make a subprocess.call in order to execute confChamber.py

It looks to me that refactoring the code a bit to call python functions rather then scripts through subprocess.call will be better in terms of code readability and eventual debugging

**Comment by bdorney** [comment]
@mexanick can you provide a more detailed example of what you are requesting?  Maybe using the new repo issue template?

**Comment by bdorney** [comment]
Seems like `run_scans.py` and probably also:

- `confAllChambers.py`
- `gem-plotting-tools/ana_scans.py`

Are invoking "dummy" processes for each call which lead to communication problems as described at:

 http://cmsonline.cern.ch/cms-elog/1006872

**Comment by mexanick** [comment]
Closing and opening new issue using new templates
