### ISSUE TITLE
ContReg3 in confChamber.py

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#79]
Is this write operation done multiple times per VFAT?:
[L69](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0feebd8ea4e527795fc7e3c749fd1a4f4a020e60/confChamber.py#L69)
[L95](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/0feebd8ea4e527795fc7e3c749fd1a4f4a020e60/confChamber.py#L95)

**Comment by cbravo135** [comment]
Yeah, but this is not the routine typically used by the shifter. This is only used by the expert during development of new configurations. I agree we could make it write this only once.

**Comment by bdorney** [comment]
These line numbers are no longer current.  Do we know what commit this is on?  Is this still relevant?

**Comment by jsturdy** [comment]
Updated to use specific commit hash, I think it's only a potential issue in the future, depending on the use case

**Comment by mexanick** [comment]
Close as outdated
