### ISSUE TITLE
Make anaUltraScurve save utime value from input file

### ISSUE THREAD

**Issue by ReyerBand** [cms-gem-daq-project/vfatqc-python-scripts#84]
ultraScurve.py currently saves the utime of the scan to scurveTree, but this value is not passed on to scruveFitTree in anaUltraScurve.py

**Comment by cbravo135** [comment]
Go for it @ReyerBand

**Comment by bdorney** [comment]
Is this still needed?

**Comment by jsturdy** [comment]
Doubtful
