### ISSUE TITLE
Skip scanning of channels that are masked

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#85]
Currently, in ```ultraScurve``` even if certain channels are masked during the ```confChamber``` step (or by other means), an s-curve will be taken for that channel.
Probably this is useless, and an obvious candidate for optimization.
Simplest would be to skip the scan, and fill the tree with default values

**Comment by cbravo135** [comment]
This would have to mean the same channel is masked on every VFAT. I do not think this is likely to happen ever.

**Comment by jsturdy** [comment]
Ah right, that's the piece I was forgetting
