### ISSUE TITLE
Need requirements file

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/vfatqc-python-scripts#9]
Need to add the equivalent of a ```pip``` requirements file to ensure correct versions of necessary ```python``` modules are available.  Here's what are on ```gem904daq01``` that I believe are related
* ```numpy (1.11.2)```
* ```matplotlib (1.5.3)```
* ```scipy (0.18.1)```

**Comment by cbravo135** [comment]
Is this still relevant?
