### ISSUE TITLE
anaUltraThresholds.py crashes when using the --vfatmask flag

### ISSUE THREAD

**Issue by lmoureaux** [cms-gem-daq-project/vfatqc-python-scripts#97]
Using anaUltraThresholds.py with the `--vfatmask=0xF40400` option leads to a crash at line 249:

    [...]
    Saving vt1Max distributions
    Traceback (most recent call last):
      File "/home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/macros/anaUltraThreshold.py", line 249, in 
        dict_hMaxVT1[vfat].Draw("hist")
    KeyError: 10

The crash occurs because the elements in dict_hMaxVT1 are created for non-masked VFATs only, but used for every VFAT. The '10' above is the index of the first masked VFAT.

See also http://cmsonline.cern.ch/cms-elog/996439

### Type of issue

- [x] Bug report
- [ ] Feature request

**Comment by bdorney** [comment]
By changing the initialization of the dictionaries created in anaUltraThresholds.py you can remove the need for vfatmask entirely.

I've solved this on my develop branch...I'll have a PR "soon."

**Comment by bdorney** [comment]
We can close this issue, it was addressed in:

https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/4
